Not to log class name
Now, the log message contains the class name:
  2021-12-19 22:59:31,787 ERROR [main] org.fluentd.logger.sender.RawSocketSender
  java.net.ConnectException: Connection refused (Connection refused)

Since log frameworks usually have a way to log class name without the
need to include it in the log message, the class name should be removed.
The following text shows a sample log mesage after this change:

  2021-12-19 22:56:58,842 ERROR [main] flush failed
  java.net.ConnectException: Connection refused (Connection refused)

Signed-off-by: Jingguo Yao <yaojingguo@gmail.com>